// Typed access to the published benchmark aggregates (generated by `python -m fineprint.export`).
// Model-level only — no contract identities — so it is safe to ship in the public bundle.
import raw from "./data.json";

export type ModelRow = {
  id: string;
  label: string;
  family: string;
  brand: string;         // lab id -> provider logo
  new: boolean;
  est: boolean;
  accuracy: number;      // combined % correct (extraction + convention)
  extraction: number;    // % correct on economic facts (dates, fee-set, amounts, overrides)
  convention: number;    // % correct on house-convention fields (timing, period, credit type)
  halluc: number;        // % of HIGH-confidence answers that were wrong
  consistency: number;   // mean run-to-run σ across the N runs
  cost_1k: number;       // USD per 1,000 contracts
  cost_contract: number;
  p50: number;           // median latency, seconds
  p90: number;
  avg_lat: number;
  in_tok: number;
  out_tok: number;
  reasoning: number;
  reliability: number;   // % of calls that returned valid structured output
  value: number;         // accuracy points per $/1k
  avg_scored: number;
  calls: number;
  rank: number;
};

export type ContractMatrix = {
  labels: string[];                  // anonymized: "Doc A".."Doc F"
  difficulty: (number | null)[];     // mean accuracy across models, per document
  matrix: Record<string, (number | null)[]>;  // model id -> accuracy per document
};

export type Benchmark = {
  rows: ModelRow[];
  n_runs: number;
  n_contracts: number;
  n_models: number;
  fields_per_contract: number;
  total_judgments: number;
  baseline_acc: number | null;
  baseline_label?: string | null;
  newest_id: string | null;
  contracts?: ContractMatrix;
};

export const data = raw as Benchmark;

export const models = data.rows;
export const byId = (id: string) => models.find((m) => m.id === id);
export const newest = () => models.find((m) => m.id === data.newest_id) ?? models[0];

export const money = (n: number) =>
  n >= 100 ? `$${Math.round(n)}` : `$${n.toFixed(n < 10 ? 2 : 1)}`;

export const BASELINE_LABEL = "GPT-5.5";
